# Generated by Django 5.0.4 on 2024-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
